### ISSUE TITLE
CEEMDAN-LSTM问题咨询

### ISSUE THREAD

**Issue by zhichonglyu** [pp-jia/stock_task#1]
你好，我对CEEMDAN-LSTM非常感兴趣，看到你的代码，冒昧问一下能否添加了联系方式，探讨下相关内容，谢谢@！！

**Comment by pp-jia** [comment]
发你邮件了，有时间请查看。

**Comment by zhichonglyu** [comment]
你好，给你发邮件了哈，麻烦你看下邮件谢谢！
